In [4]:
import pandas as pd
import simplejson as json
from pprint import pprint
from tqdm import tqdm
import pickle

from sklearn.model_selection import train_test_split

In [5]:
files = ['mpd.slice.0-999.json'
,'mpd.slice.1000-1999.json'
,'mpd.slice.2000-2999.json'
,'mpd.slice.3000-3999.json'
,'mpd.slice.4000-4999.json'
,'mpd.slice.5000-5999.json'
,'mpd.slice.6000-6999.json'
,'mpd.slice.7000-7999.json'
,'mpd.slice.8000-8999.json'
,'mpd.slice.9000-9999.json']

In [6]:
def get_sigle_playlist_file(filename):
    with open(filename,'r') as f:
        data = json.load(f)
    return pd.DataFrame(data['playlists'])

In [7]:
ls_df_playlists = []
for f_name in tqdm(files):
    ls_df_playlists.append(get_sigle_playlist_file("../data/"+f_name))
df_playlists = pd.concat(ls_df_playlists, ignore_index=True)
df_playlists

100%|██████████| 10/10 [00:02<00:00,  3.51it/s]

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,Throwbacks,false,0,1493424000,52,47,1,"[{'pos': 0, 'artist_name': 'Missy Elliott', 't...",6,11532414,37,NaN
1,Awesome Playlist,false,1,1506556800,39,23,1,"[{'pos': 0, 'artist_name': 'Survivor', 'track_...",5,11656470,21,NaN
2,korean,false,2,1505692800,64,51,1,"[{'pos': 0, 'artist_name': 'Hoody', 'track_uri...",18,14039958,31,NaN
3,mat,false,3,1501027200,126,107,1,"[{'pos': 0, 'artist_name': 'Camille Saint-Saën...",4,28926058,86,NaN
4,90s,false,4,1401667200,17,16,2,"[{'pos': 0, 'artist_name': 'The Smashing Pumpk...",7,4335282,16,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,rap,false,9995,1491782400,34,26,1,"[{'pos': 0, 'artist_name': 'Lecrae', 'track_ur...",16,8530582,15,NaN
9996,Blues,false,9996,1482364800,57,48,1,"[{'pos': 0, 'artist_name': 'Robert Johnson', '...",15,13010049,30,NaN
9997,game songs,false,9997,1508371200,27,24,4,"[{'pos': 0, 'artist_name': 'NateWantsToBattle'...",23,5104068,7,NaN
9998,country,false,9998,1466208000,12,12,1,"[{'pos': 0, 'artist_name': 'Little Big Town', ...",3,2459585,12,NaN
9999,Country jams,false,9999,1492905600,55,41,3,"[{'pos': 0, 'artist_name': 'Granger Smith', 't...",22,11604099,33,NaN

In [15]:
def get_track_id_in_playlist(playlist):
    return [x['track_uri'] for x in playlist['tracks']]

In [16]:
df_playlists['tracks'] = df_playlists.apply(get_track_id_in_playlist,axis=1)
df_playlists

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,Throwbacks,false,0,1493424000,52,47,1,"[spotify:track:0UaMYEvWZi0ZqiDOoHU3YI, spotify...",6,11532414,37,NaN
1,Awesome Playlist,false,1,1506556800,39,23,1,"[spotify:track:2HHtWyy5CgaQbC7XSoOb0e, spotify...",5,11656470,21,NaN
2,korean,false,2,1505692800,64,51,1,"[spotify:track:74tqql9zP6JjF5hjkHHUXp, spotify...",18,14039958,31,NaN
3,mat,false,3,1501027200,126,107,1,"[spotify:track:4WJ7UMD4i6DOPzyXU5pZSz, spotify...",4,28926058,86,NaN
4,90s,false,4,1401667200,17,16,2,"[spotify:track:4iCGSi1RonREsPtfEKYj5b, spotify...",7,4335282,16,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,rap,false,9995,1491782400,34,26,1,"[spotify:track:0hAUGZg91bjp2isiMCr1of, spotify...",16,8530582,15,NaN
9996,Blues,false,9996,1482364800,57,48,1,"[spotify:track:7zSKmt2QD3yf4Rkb2MSuAf, spotify...",15,13010049,30,NaN
9997,game songs,false,9997,1508371200,27,24,4,"[spotify:track:46ZY3cPpxVCMShhdkOD8gE, spotify...",23,5104068,7,NaN
9998,country,false,9998,1466208000,12,12,1,"[spotify:track:5pD1qwHvnKFcQ2qjwsoKYF, spotify...",3,2459585,12,NaN
9999,Country jams,false,9999,1492905600,55,41,3,"[spotify:track:6naYpFIKihKbGg6lGxpveI, spotify...",22,11604099,33,NaN

In [17]:
df_train,df_test = train_test_split(df_playlists,test_size=0.2,random_state=42)

In [18]:
df_train

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
9254,NOLA,false,9254,1507939200,66,61,1,"[spotify:track:0nMqu5vN44GNv8UOQxmBJK, spotify...",17,14752318,56,NaN
1561,H2O,false,1561,1385596800,43,43,1,"[spotify:track:2ag8U9ccVmjBjia5qNZPDH, spotify...",17,9915452,42,NaN
1670,THE MIX,false,1670,1472083200,62,58,2,"[spotify:track:11bD1JtSjlIgKgZG2134DZ, spotify...",7,15286108,47,NaN
6087,Peaceful,false,6087,1507593600,106,98,1,"[spotify:track:152lZdxL1OR0ZMW6KquMif, spotify...",24,24124550,81,NaN
6669,New,false,6669,1489449600,16,15,1,"[spotify:track:0VYCUWNFIYLIOQqu3bFzs0, spotify...",11,4071423,13,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
5734,Country,false,5734,1451779200,223,152,3,"[spotify:track:1mJ05BN0So26a14iib85aI, spotify...",4,48199560,70,NaN
5191,Folk,false,5191,1508716800,107,51,1,"[spotify:track:21pL95f63XT8Mezt8qPOtq, spotify...",15,21989208,43,NaN
5390,jams,false,5390,1509408000,101,79,1,"[spotify:track:3DXncPQOG4VBw3QHh3S817, spotify...",34,21776300,61,NaN
860,work,false,860,1493424000,50,43,1,"[spotify:track:4SibKHGH0Nql4sZwOweCh2, spotify...",17,12286033,39,NaN
7270,Throw Back,false,7270,1470614400,51,32,1,"[spotify:track:3d8PDk3B4am5c6TsUCznUW, spotify...",14,13171627,29,NaN

In [19]:
df_test

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
6252,Gym,false,6252,1486598400,30,28,1,"[spotify:track:3CzOoYfw7mj5jMHGsJp9TG, spotify...",10,6771523,19,NaN
4684,BOSSanova,false,4684,1498176000,20,13,1,"[spotify:track:0wrx7YMUJXIcThebT8XDz5, spotify...",5,4473182,10,NaN
1731,Disney,false,1731,1502496000,55,27,1,"[spotify:track:4T9Jpft8jvZAP57aE3VdCt, spotify...",3,10028526,39,NaN
4742,Trap,false,4742,1487980800,30,30,2,"[spotify:track:5c1Miz53kZbsJFoa6RvS99, spotify...",4,6434496,27,NaN
4521,Jesus,false,4521,1482537600,80,53,1,"[spotify:track:1wRZLcT8k5oQrf34dRBQb4, spotify...",16,24548027,43,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
6412,driving,false,6412,1469577600,45,41,1,"[spotify:track:3KD51YetMdgdPRSF42E35w, spotify...",4,10615480,37,NaN
8285,Smooth rock,false,8285,1502841600,41,22,1,"[spotify:track:48UPSzbZjgc449aqz8bxox, spotify...",5,10711921,14,NaN
7853,heavy,false,7853,1440374400,17,16,1,"[spotify:track:2yuSLHwPoOoB1zDuXnQnqZ, spotify...",4,5568780,7,NaN
1095,Pop en español,false,1095,1485820800,86,53,1,"[spotify:track:5vNocq26ujTMI4L8bECuGk, spotify...",43,20344685,32,NaN
6929,Summer2016,false,6929,1468713600,43,40,3,"[spotify:track:05kVyNUR9uibHta4jcGTTv, spotify...",7,11694894,38,NaN

In [20]:
with open('../data/train_playlist.pkl','wb') as f:
    df_train.to_pickle(f)

with open('../data/test_playlist.pkl','wb') as f:
    df_test.to_pickle(f)